test/test_datapipe.py

Stack from [ghstack](https://github.com/ezyang/ghstack):
* #19
* __->__ #18

Change test_datapipe to run with unittest.main()

---

.github/workflows/test_release.yml

Update release branch of TorchData fro GHA workflow

[Release 0.3.0] Set release branch for workflow

---

docs/source/conf.py

Change doc version to beta

---

.github/workflows/_build_test_upload.yml
.github/workflows/docs.yml

PR landed into main branch https://github.com/pytorch/data/pull/254

[Release 0.3.0] Implement auto doc gen for release

---

.github/workflows/ci.yml
.github/workflows/domain_ci.yml

[Release 0.3.0] Add Python 3.10 test

---

.github/workflows/_build_test_upload.yml
.github/workflows/nightly_release.yml
.github/workflows/release.yml
.github/workflows/test_release.yml
setup.py

[Release 0.3.0] Fix bugs for setup and CI (Dep & PyTorch Version)

---

.github/workflows/_build_test_upload.yml
.github/workflows/nightly_release.yml
.github/workflows/release.yml
.github/workflows/test_release.yml
setup.py

Revert "[Release 0.3.0] Fix bugs for setup and CI (Dep & PyTorch Version)"

---

README.md
docs/README.md

Release version of #264 which will be landed into `main`

Updating README for beta release 

---

.github/workflows/_build_test_upload.yml
.github/workflows/nightly_release.yml
.github/workflows/release.yml
.github/workflows/test_release.yml
setup.py

#266 is landed into main
Reland of #265

[Release 0.3.0] Re-land Fix bugs for setup and CI (Dep & PyTorch Version)

---

examples/text/amazonreviewpolarity.py

Merging https://github.com/pytorch/data/pull/271 into release branch

Adding detailed comments for Amazon Review example

---

.github/workflows/_build_test_upload.yml
.github/workflows/nightly_release.yml
.github/workflows/release.yml
.github/workflows/test_release.yml

[Release 0.3.0] Revamp release CI to support artifact cache and conda uploading

---

docs/source/examples.rst

Adding more usage examples, the 0.3.0 version of the following that has landed in `main`
* #277

[Release 0.3.0] Adding more usage examples

---

.github/workflows/_build_test_upload.yml

[Release 0.3.0] Fix PYPI upload

---

docs/source/conf.py

[Release 0.4.0] Bump doc version to 0.4.0

---

.flake8

Cherrypicked from the PR in main branch: https://github.com/pytorch/data/pull/446

[Release 0.4.0] Remove docs from flake8

---

README.md

Cherry-pick Ref: https://github.com/pytorch/data/pull/455

[Release 0.4.0] Fix installation doc (#455)

---

test/test_remote_io.py

Cherry-picked PR in main branch: https://github.com/pytorch/data/pull/461

Temporarily disable AWSSDK functional tests (#461)

---

torchdata/datapipes/iter/transform/bucketbatcher.py
torchdata/datapipes/iter/util/hashchecker.py

Small fix to functional name and usage example.
Cherry-pick of this merged PR https://github.com/pytorch/data/pull/440

[Release 0.4.0] Small fix to functional name and usage example (#440)

---

README.md
docs/source/torchdata.datapipes.map.rst
docs/source/tutorial.rst

Updating the tutorial and README with more relevant/correct information. Minor fix to one part of `MapDataPipe` documentation as well.
Cherry-pick of this merged PR https://github.com/pytorch/data/pull/458

[Release 0.4.0] Fixing tutorial with DataLoader (#458)

---

torchdata/datapipes/iter/load/online.py

Ref from main branch: https://github.com/pytorch/data/pull/442
Summary:
Fixes https://github.com/pytorch/data/issues/204
The Google Drive links used to download certain datasets takes us to a page like the following (the screenshot is from https://drive.google.com/uc?export=download&id=0Bz8a_Dbh9QhbUkVqNEszd0pHaFE):
It seems like the previous method for dealing with this via the `download_warning` cookie is no longer working. Instead it seems Google Drive now always uses "t" as the confirm_token. My patch sets the confirm_token if it detects the "Download anyway" string in the page.
Pull Request resolved: https://github.com/pytorch/data/pull/442
Differential Revision: D36639307
fbshipit-source-id: 33d71e9d8b75ae75758a4eacd3e5a7ffdfb00b6c
Please read …

[Release 0.4.0] GDriveReader: handle Virus Scan Warning using confirm=t (#442)

---

README.md
test/test_remote_io.py
torchdata/datapipes/iter/load/README.md

Ref on main branch: #464
Summary:
Fixes https://github.com/pytorch/data/issues/460
- update the s3 test cases due to an update in the public dataset
Pull Request resolved: https://github.com/pytorch/data/pull/464
Differential Revision: D36678285
fbshipit-source-id: 5e579d20290aec0f4f0a17031fe1bb256a640231
Fixes …

[Release 0.4.0] update s3 test cases (#464)

---

.github/workflows/_build_test_upload.yml
.github/workflows/ci.yml
README.md
packaging/build_wheel.sh
packaging/torchdata/meta.yaml
test/requirements.txt
test/test_tfrecord.py
torchdata/datapipes/iter/load/README.md

Ref on main branch: #471
Summary:
Fixes https://github.com/pytorch/data/issues/470
- Add `test/requirements.txt` to specify test dependencies
- Specify `protobuf` version smaller than 4
- Remove redundant `numpy` requirements
- Fix lint error on main branch
Pull Request resolved: https://github.com/pytorch/data/pull/471
Differential Revision: D36702476
fbshipit-source-id: 00554128e89a0fb4fc5157495ec3d20ffb4d6396

[Release 0.4.0] Fix TF Record test (#471)

---

mypy.ini
test/requirements.txt
test/test_huggingface_datasets.py
test/test_serialization.py
torchdata/datapipes/iter/__init__.py
torchdata/datapipes/iter/load/huggingface.py

Cherry-pick of https://github.com/pytorch/data/pull/490 for release

[Release 0.4.0] Add support for hf `datasets` reader (#490)

---

.github/workflows/lint.yml
README.md
docs/source/conf.py
docs/source/torchdata.datapipes.utils.rst
docs/source/tutorial.rst
examples/vision/imagefolder.py
mypy.ini
test/test_local_io.py
torchdata/datapipes/utils/__init__.py
torchdata/datapipes/utils/_visualization.py

Cherry-pick of these PRs for release:
* https://github.com/pytorch/data/pull/330
* https://github.com/pytorch/data/pull/504

[Release 0.4.0] Adding utility function to visualize DataPipe graphs

---

docs/source/_templates/function.rst
docs/source/torchdata.datapipes.utils.rst
torchdata/datapipes/utils/_visualization.py

Cherry-pick of the following PR for release:
* https://github.com/pytorch/data/pull/504

[Release 0.4.0] Improve graph visualization documentation

---

.github/workflows/release.yml

Change branch and pytorch version for TorchData 0.4.0 release

[Release 0.4.0] Enable official release

---

.github/workflows/_build_test_upload.yml

Summary:
The target folder for the official release is corrected.
Pull Request resolved: https://github.com/pytorch/data/pull/521
Differential Revision: D37250367
fbshipit-source-id: 582ec710b46f5f47cab4042bcb69f79ae7c44a85

[0.4.0] Fix target folder for official release (#521)

---

examples/text/CC100.ipynb
examples/text/ag_news.py
examples/text/amazonreviewpolarity.py
examples/text/examples_usage.ipynb
examples/text/imdb.py
examples/text/squad1.py
examples/text/squad2.py

Cherry-pick of #524 for release

[0.4.0] Update examples to avoid lambdas

---

torchdata/dataloader2/README.md

Summary:
Add brief description of `DataLoader2` and related components.
Pull Request resolved: https://github.com/pytorch/data/pull/526
Differential Revision: D37315170
fbshipit-source-id: 9886fb60c48870815c4e8242eb46e69031abba9a

Add README for DataLoader2 (#526)

---

torchdata/datapipes/iter/load/README.md
torchdata/datapipes/iter/load/s3io.py

Summary:
Per title
Pull Request resolved: https://github.com/pytorch/data/pull/542
Reviewed By: VitalyFedyunin
Differential Revision: D37389586
fbshipit-source-id: 7437ea488fb80b87e8f52b133c83d8990be8db02

Fix S3 documentation (#542)

---

README.md
docs/source/examples.rst
docs/source/tutorial.rst
torchdata/dataloader2/README.md

Cherry-pick of these PRs for release:
* #541
* #543 
cc: @ejguan

[Release 0.4.0] Update DataLoader2 README and fix broken links in doc

---

.github/workflows/_build_test_upload.yml

Summary:
Found the issue during official release
Pull Request resolved: https://github.com/pytorch/data/pull/556
Differential Revision: D37492010
fbshipit-source-id: 59975e6da6bdf766ee07aa99709983994c2f7e77

Fix binary path for official release (#556)

---

docs/source/conf.py

[Release 0.4.1] Bump doc version

---

versions.html

Bump version release doc to 0.4.1

---

.github/workflows/release.yml

[Release 0.4.1] Enable official release

---

.github/workflows/_build_test_upload.yml

Fix conda install local package for nightly release

---

docs/source/conf.py

[Release 0.5.0] Bump doc version to 0.5.0

---

.github/workflows/lint.yml
docs/source/conf.py
docs/source/torchdata.datapipes.iter.rst
docs/source/tutorial.rst
test/dataloader2/test_random.py
test/test_dataloader2.py
test/test_distributed.py
torchdata/_constants.py
torchdata/dataloader2/communication/eventloop.py
torchdata/dataloader2/communication/protocol.py
torchdata/dataloader2/dataloader2.py
torchdata/dataloader2/reading_service.py
torchdata/datapipes/iter/transform/bucketbatcher.py
torchdata/datapipes/iter/util/prefetcher.py
torchdata/datapipes/iter/util/randomsplitter.py

PRs listed here: https://github.com/pytorch/data/issues/805#issuecomment-1279513192

[Release 0.5.0] Cherrypicking the PRs for the week of Oct 17

---

.github/workflows/_build_test_upload.yml
test/requirements.yml

Try to make sure conda build is working properly on the new image

Enable Conda release with manylinux image

---

test/dataloader2/test_random.py
test/test_distributed.py

Summary:
See the issue https://github.com/pytorch/data/issues/857
Pull Request resolved: https://github.com/pytorch/data/pull/858
Reviewed By: NivekT, dahsh
Differential Revision: D40646733
fbshipit-source-id: 346151425cab53a236079311adee8a8d6364b0f4

Temporarily skip distributed testing for ProtoMPRS on Windows (#858)

---

docs/source/conf.py

[Release 0.5.1] Bump doc version

---

test/test_remote_io.py

Cherry pick PRs that fix S3 tests

---

.github/workflows/release.yml

[Release 0.5.1] Enable official release

---

.github/workflows/_build_test_upload.yml
packaging/build_conda.sh

Revert "3.11 Conda for Mac/Windows"

---

docs/source/conf.py

[Release 0.6.0] Bump doc version to 0.6.0

---

docs/source/torchdata.datapipes.iter.rst

Cherrypick: #1046
Summary:
Per title
Pull Request resolved: https://github.com/pytorch/data/pull/1046
Differential Revision: D43579347
fbshipit-source-id: 622fd646c377f8b32e11f08fd765b123cee5532f

Add pin_memory to online doc (#1046)

---

docs/source/dp_tutorial.rst
docs/source/examples.rst
docs/source/reading_service.rst
docs/source/torchdata.datapipes.utils.rst
test/test_iterdatapipe.py
torchdata/datapipes/iter/transform/callable.py
torchdata/datapipes/map/util/unzipper.py

[Release 0.6.0] Slicer and doc improvements

---

.github/workflows/release.yml

[Release 0.6.0] Enable official release

---

docs/source/conf.py

[Release 0.6.1] Bump doc version

---

.github/workflows/_build_test_upload.yml

Cherry-pick torchdata arm64 build

Fix arm64 builds by building using source

---

.github/workflows/_build_test_upload.yml

Build using dedicated wheel environment. Different for each python version

Build using dedicated wheel environment

---

versions.html

Update versions.html for 0.7

---

test/stateful_dataloader/test_state_dict.py

Remove unnecessary print

---

test/stateful_dataloader/test_state_dict.py
torchdata/stateful_dataloader/stateful_dataloader.py
torchdata/stateful_dataloader/worker.py

fix for iter called twice

---

.github/workflows/stateful_dataloader_ci.yml
test/requirements.txt
test/stateful_dataloader/test_hugging_face.py

Duplicate of #1274 which merged in the wrong order, doh
-
-

add HF test again

---

.github/workflows/build_conda_linux.yml
.github/workflows/build_wheels_linux.yml

See following: https://github.com/pytorch/data/blob/main/.github/workflows/build-wheels-m1.yml

Fix linux wheels and conda on condition

---

packaging/pkg_helpers.bash

To conform with https://pytorch.org/get-started/locally/
```
pip3 install torch --index-url https://download.pytorch.org/whl/test/cpu
```

Fix torch install instructions

---

.github/workflows/_build_test_upload.yml
.github/workflows/test_release.yml

As per following: https://github.com/JamesIves/github-pages-deploy-action/discussions/1431

Fix doc build

---

README.md

Update README with 0.8.0 release info

---

.github/workflows/test_release.yml

Andrewkh/update test release to 0.9

---

.github/workflows/test_release.yml

update test-release.yml (#1324)

---

test/smoke_test/smoke_test.py

* stateful dl smoke test
Summary:
Test Plan:
Reviewers:
Subscribers:
Tasks:
Tags:
* remove version check
-
-

stateful dl smoke test (#1300)

---

.github/workflows/aistore_ci.yml
.github/workflows/ci.yml
.github/workflows/lint.yml
.github/workflows/stateful_dataloader_ci.yml
CONTRIBUTING.md
README.md
packaging/pkg_helpers.bash

Cherry Pick #1336 to release branch
-
-

Andrewkh/update nightly channel (#1336)

---

.github/workflows/_build_test_upload.yml

fix test install path (#1340)

---

test/nodes/test_map.py

Remove some leftover debugging prints from test_map
-
-

remove prints from test_map

---

packaging/pre_build_script_linux.sh

Use zlib rather then zlib-static

Update pre_build_script_linux.sh use zlib

---

torchdata/nodes/map.py

It's a pain to switch between inline vs parallel Mapping. This change enables users to switch seamlessly by creating a separate "Inline" iterator. Updates "Mapper" to be a builder function which returns ParallelMapper(..., num_workers=0)
Test Plan: Existing unit tests since this should be fully backwards compatible with no behaviour changes.
#1374
-

Consolidate Mapper and ParallelMapper

---

test/nodes/test_multi_node_weighted_sampler.py
torchdata/nodes/__init__.py

Fixes [#{1373}](https://github.com/pytorch/data/issues/1373)

make StopCriteria available in torchdata.nodes import

---

torchdata/nodes/README.md

We need a landing page. We can add links to examples from here. Can be used as a starting point for proper pytorch.org docs 
https://github.com/pytorch/data/issues/1352

Add a README for torchdata.nodes

---

test/nodes/test_snapshot_store.py

Run each potentially flaky test 10 times, raise in worker instead of exiting to more reliably kill thread

Fix test flakiness and test for it

---

test/nodes/test_multi_node_weighted_sampler.py
test/nodes/utils.py
torchdata/nodes/batch.py
torchdata/nodes/loader.py
torchdata/nodes/map.py
torchdata/nodes/pin_memory.py
torchdata/nodes/prefetch.py
torchdata/nodes/samplers/multi_node_weighted_sampler.py
torchdata/nodes/snapshot_store.py

Adding doc strings ahead of new release 

---

README.md

Updating README.md in release branch to reflect v0.10

update readme in release branch v10

---

.github/workflows/build_wheels_linux.yml

Need to pin to release/2.5.1 to aovid trying to pull 2.6.0

pin test-infra-ref

---

docs/source/what_is_torchdata_nodes.rst

fix docs performance section

---

examples/vision/imagefolder.py
test/stateful_dataloader/test_dataloader.py

Codemodded with TorchFix https://github.com/pytorch-labs/torchfix/

Use default_collate from public API

---

.github/workflows/test_release.yml

Updating release and PyTorch version

update test_release.yml to v0.11

---

test/stateful_dataloader/test_sampler.py
test/stateful_dataloader/test_state_dict.py
torchdata/stateful_dataloader/sampler.py
torchdata/stateful_dataloader/stateful_dataloader.py

We had some changes (#1439 #1441 ) in the main branch after cutting the release branch 0.11.
Cherry-picking those changes.

Cherry-picking changes in main to the release branch

---

0.11/genindex.html
0.11/getting_started_with_torchdata_nodes.html
0.11/index.html
0.11/migrate_to_nodes_from_utils.html
0.11/objects.inv
0.11/py-modindex.html
0.11/search.html
0.11/stateful_dataloader_tutorial.html
0.11/torchdata.nodes.html
0.11/torchdata.stateful_dataloader.html
0.11/what_is_torchdata_nodes.html

- update main documentation to 0.11.0 documentation (find . -type f -name "*.html" -exec sed -i 's/main documentation/0.11.0 documentation/g' {} \;)
- update main (0.11.0+377e64c ) to 0.11.0 (find . -type f -name "*.html" -exec sed -i 's/main (0.11.0+377e64c )/0.11.0/g' {} \;) also find . -type f -name "*.inv" -exec sed -i 's/main (0.11.0+377e64c )/0.11.0/g' {} \; for objects.inv

update docs for 0.11.0 release

---

torchdata/nodes/loader.py

Fixes Loader's state num_yielded off by 1 after loading state

---

CONTRIBUTING.md
README.md
docs/source/conf.py

Removes the disclaimers about what will be removed, as that has all been removed.

Update docs to reflect current status

---

torchdata/nodes/map.py

Simple change initializing sort thread and queue only if in-order is needed.

Minor refactor in map

---

packaging/pre_build_script_linux.sh

Testing if this solves the broken CI, and what other ramifications it will have.

remove failing ninja-build
