pytorch/data

setup.py
Without this and if the environment variable `PYTORCH_VERSION` exists but is unset,  
https://github.com/pytorch/data/blob/116443308b60409084ad8f97e10ced082efb9123/setup.py#L44-L45
is triggered, which leads the setup to look for `torch==`, which fails.
=> make pytorch version detection more robust

test/test_datapipe.py
Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #19
* #18
Fixes the issues #19 and fixes #15
=> Make test_JSON_parser reads files in a consistent order

docs/source/torchdata.datapipes.iter.rst, examples/audio/librispeech.py, examples/text/amazonreviewpolarity.py, examples/text/imdb.py, examples/vision/caltech101.py, examples/vision/caltech256.py, test/test_local_io.py, test/test_remote_io.py, torchdata/datapipes/gen_pyi.py, torchdata/datapipes/iter/__init__.py, torchdata/datapipes/iter/__init__.pyi, torchdata/datapipes/iter/__init__.pyi.in, torchdata/datapipes/iter/util/decompressor.py, torchdata/datapipes/iter/util/tararchiveloader.py, torchdata/datapipes/iter/util/xzfileloader.py, torchdata/datapipes/iter/util/ziparchiveloader.py
Merging a PR that has landed to main to release 0.3.0.
--
* https://github.com/pytorch/data/pull/243
Renaming Archive readers to loaders, and extractor to decompressor.
Note that the old ones are still functional, but excluded from the documentation and .pyi file. There is no deprecation warnings for them (we can add them after the first release).
=> [Release 0.3.0] Renaming Archive readers to loaders, and extractor to decompressor

docs/source/conf.py, docs/source/torchdata.datapipes.iter.rst, torchdata/datapipes/iter/load/fsspec.py, torchdata/datapipes/iter/load/iopath.py, torchdata/datapipes/iter/load/online.py, torchdata/datapipes/iter/transform/bucketbatcher.py, torchdata/datapipes/iter/transform/flatmap.py, torchdata/datapipes/iter/util/cacheholder.py, torchdata/datapipes/iter/util/combining.py, torchdata/datapipes/iter/util/cycler.py, torchdata/datapipes/iter/util/dataframemaker.py, torchdata/datapipes/iter/util/decompressor.py, torchdata/datapipes/iter/util/hashchecker.py, torchdata/datapipes/iter/util/header.py, torchdata/datapipes/iter/util/indexadder.py, torchdata/datapipes/iter/util/jsonparser.py, torchdata/datapipes/iter/util/paragraphaggregator.py, torchdata/datapipes/iter/util/plain_text_reader.py, torchdata/datapipes/iter/util/rararchiveloader.py, torchdata/datapipes/iter/util/rows2columnar.py, torchdata/datapipes/iter/util/samplemultiplexer.py, torchdata/datapipes/iter/util/saver.py, torchdata/datapipes/iter/util/tararchiveloader.py, torchdata/datapipes/iter/util/unzipper.py, torchdata/datapipes/iter/util/xzfileloader.py, torchdata/datapipes/iter/util/ziparchiveloader.py
Merging a PR that has landed to main to release 0.3.0.
--
* https://github.com/pytorch/data/pull/249
Adding usage examples to all IterDataPipes
=> [Release 0.3.0] Adding usage examples to all IterDataPipes

torchdata/datapipes/gen_pyi.py
For release 0.3.0, we do not want users to execute this file. Therefore, we add an exception to disable it.
=> Adding an exception to prevent gen_pyi.py from being ran

.github/workflows/_build_test_upload.yml
Forward fix for #274
Docker image requires to install `aws` using root permission rather than `user`. Otherwise, we can not invoke `aws`
Before this PR: https://github.com/pytorch/data/runs/5424789165?check_suite_focus=true
After this PR: https://github.com/pytorch/data/runs/5424716846?check_suite_focus=true
The same fix will be patched in #270 for main branch
=> [Release 0.3.0] Fix aws upload

.github/workflows/_build_test_upload.yml
Ref on main branch: #486
Summary:
Add the missing env variable `WORKSPACE` to the workflow.
See: https://github.com/pytorch/data/runs/6687888202?check_suite_focus=true#step:8:107
Pull Request resolved: https://github.com/pytorch/data/pull/486
Differential Revision: D36810167
fbshipit-source-id: 3a82646ebf6ef36fd4586fb543b316045160c346
=> Fix workspace path (#486)

docs/source/tutorial.rst
Ref on main branch: #487
Summary:
See the feedback from a user: https://github.com/pytorch/data/issues/454#issuecomment-1143256345
We should explicitly ask users to place `sharding_filter` as early as possible.
Pull Request resolved: https://github.com/pytorch/data/pull/487
Reviewed By: wenleix
Differential Revision: D36812259
fbshipit-source-id: 4c983f3216a80be398f85b20871e65b0e41627e0
=> Update tutorial about placing sharding_filter (#487)

test/test_fsspec.py, test/test_local_io.py, torchdata/datapipes/iter/load/fsspec.py, torchdata/datapipes/iter/load/iopath.py
Ref on main branch: #463
Summary:
Fixes https://github.com/pytorch/data/issues/387
- Adds `list_file()` method on `IoPathFileListerIterDataPipe`
- Adds `list_file()` method on `FSSpecFileListerIterDataPipe`
- Add tests for those methods
I feel as if the implementation is quite naive. Would appreciate any feedback on it.
Pull Request resolved: https://github.com/pytorch/data/pull/463
Differential Revision: D36777142
fbshipit-source-id: 1c4474776f3fcd377ae545bd8bd7bf26d0b2fa88
=> Add list_file() functional API to FSSpecFileLister and IoPathFileLister (#463)

test/requirements.txt, test/test_remote_io.py, torchdata/datapipes/iter/load/fsspec.py, torchdata/datapipes/iter/load/s3io.py
Ref on main branch: #495
Summary:
Fixes https://github.com/pytorch/data/issues/494
- Add `kwargs` to all `DataPipe`s using `fsspec`
- Fix a bug in `FSSpecFileLister` to prevent joining paths from the root path if the root path has already presented in the paths.
- Add/Fix more tests
I need this PR to test the performance between `fsspec` and native `s3`
Pull Request resolved: https://github.com/pytorch/data/pull/495
Differential Revision: D36908570
fbshipit-source-id: 93da4c1c7e18012fb053799265375124d28a856c
-
-
=> Improve fsspec DataPipe to accept extra keyword arguments (#495)

README.md, torchdata/datapipes/iter/util/cacheholder.py
Ref on main branch: #506
Summary:
Partially fixes: https://github.com/pytorch/data/issues/441
Add instructions on how to solve `ImportError` for `portalocker`.
Pull Request resolved: https://github.com/pytorch/data/pull/506
Differential Revision: D37045053
fbshipit-source-id: a365be88cfea9f05e155d09cf476ca89b6579205
=> Add instructions about ImportError for portalocker (#506)

.github/workflows/ci.yml, .github/workflows/domain_ci.yml
Ref on main branch: #514
Currently the CI tests on release branch use the nightly PyTorch release. This PR changes tests to use RC PyTorch release when the target branch of PR is the release branch or a commit is pushed to release branch.
See the CI result for when the PR is landed (nightly channel): https://github.com/pytorch/data/runs/6867662390?check_suite_focus=true#step:8:3
See the CI result of the PR for release branch (test channel): https://github.com/pytorch/data/runs/6867788289?check_suite_focus=true#step:8:3
=> Use PyTorch RC release on release branch

README.md, test/test_local_io.py, torchdata/datapipes/iter/util/jsonparser.py
Summary:
Pull Request resolved: https://github.com/pytorch/data/pull/518
The comment of this class suggests the keyword arguments in the constructor will be passed through to the json.loads call. However, `self.kwargs` is not actually passed through to the call.
Updated the example in the README too
Reviewed By: ejguan
Differential Revision: D37162608
=> [0.4.0] Pass through kwargs to json.loads call in JsonParser (#518)

.github/workflows/_build_test_upload.yml, .github/workflows/domain_ci.yml, .github/workflows/lint.yml
Cherry-pick the PR #558
This should resolve the CI failure for mypy
Summary:
This is a follow-up PR to help resolve a few issues that I have encountered during the official release.
- Making sure the wheels for linux always following manylinux by using `auditwheel` to repair them
- Disable domain tests on release branch for both PRs and pushes
- Improve lint CI to install PyTorch from the corresponding urls for nightly/RC/official releases
Pull Request resolved: https://github.com/pytorch/data/pull/558
Differential Revision: D37496522
fbshipit-source-id: d768f656734d34420a08d82e68f29af5f14cb2a7
=> [Release 0.4.1] Improve release workflow

.github/workflows/_build_test_upload.yml
Cherry-pick #578
Linux nightly releases are broken for some days now due to a small typo in the workflow file.
Pull Request resolved: https://github.com/pytorch/data/pull/578
Reviewed By: bearzx
Differential Revision: D37716058
fbshipit-source-id: 00e03b287a0483d1769182a17817267f3ea14b9f
=> Fix typo breaking nightly build (#578)

.github/workflows/_build_test_upload.yml
Summary:
During preparing the minor release, the document folder is changed from `0.4.0` to `0.4`. For the official release, the workflow to extract target folder from tag for the official release should be modified correspondingly.
Pull Request resolved: https://github.com/pytorch/data/pull/687
Differential Revision: D38128675
fbshipit-source-id: a1e7a83881c9d4c7ab7610629da44b8dca99bb0a
=> Fix target folder for official release (#687)

.github/workflows/_build_test_upload.yml, packaging/README.md
Cherry-pick: #692
Summary:
Fixes https://github.com/pytorch/data/issues/676
- Update the workflow to compile AWSSDK and integrated on arm64 macos
- Use conda to install python since this [action](https://github.com/actions/setup-python) doesn't work with arm64b macos
- Exclude python 3.7 from arm64 macos due to the pre-compiled python binary is not available either on conda or python official website
- Use `bash -l {0}` to make sure `conda` is available across steps
- Please check the manually triggered [workflow](https://github.com/pytorch/data/runs/7528349378?check_suite_focus=true)
- Wheels: https://github.com/pytorch/data/runs/7528349378?check_suite_focus=true#step:4:1
- Conda packages: https://github.com/pytorch/data/runs/7528462809?check_suite_focus=true#step:5:1
Pull Request …
=> Enable release on Mac arm64 (#692)

.github/workflows/_build_test_upload.yml, packaging/torchdata/meta.yaml
Cherry-pick PR: #503
This is required to always upload newly built binaries.
Summary:
Based on the offline discussion with Vitaly, we want to upload TorchData nightly releases even if tests are failing.
It's required by downstream library when PyTorch Core nightly updated but TorchData nightly still depends on the previous PT Core nightly.
Pull Request resolved: https://github.com/pytorch/data/pull/503
Differential Revision: D37049785
fbshipit-source-id: f65a166daa9646eb8251c418c3a416c51d3578e4
=> Always upload TorchData nightly release (#503)

.github/workflows/_build_test_upload.yml, test/test_remote_io.py
Cherry-pick PR: #698
Summary:
- Fix conda environment for conda upload
- Extend timeout from 3 seconds to 10 seconds for S3 Lister to reduce recent flakiness of the test
Pull Request resolved: https://github.com/pytorch/data/pull/698
Differential Revision: D38215518
fbshipit-source-id: cf0cd5d3979fe2b5e86e0634b257979f93f79894
=> Add conda env for upload and extend timeout for S3 to reduce flakiness

docs/source/tutorial.rst
=> [Release 0.4.1] Cherry-pick multiple PRs related tutorial doc

.github/workflows/_build_test_upload.yml, .github/workflows/pull_release.yml
Cherry-pick PR: #706 #717
Summary:
Noticed we were getting extra conda packges from the home directory on
the M1 runners. Making this PR to reduce the amount that we're using the
home directory.
Will probably make it unwritable in the future so this is a pre-emptive
step to that.
Also adds a workflow to test the release pipelines without actually releasing a new binary.
Signed-off-by: Eli Uriegas <eliuriegas@fb.com>
Pull Request resolved: https://github.com/pytorch/data/pull/706
Reviewed By: ejguan
Differential Revision: D38406845
Pulled By: seemethere
fbshipit-source-id: 1d312c3e1db34497c546a9b842ac7ba01d2a7ee3
=> [Release 0.4.1] Install Conda in temp folder, add workflow to test release pipelines, change release type on release branch

docs/source/tutorial.rst, torchdata/datapipes/iter/load/aisio.py, torchdata/datapipes/iter/load/fsspec.py, torchdata/datapipes/iter/load/iopath.py
=> [Release 0.5.0] Adding Cloud Storage Provider tutorial section

test/test_fsspec.py, torchdata/datapipes/iter/load/fsspec.py
=> [Release 0.5.0] Adding kwargs for `fs.open()` in fsspec DataPipes

.github/workflows/_build_test_upload.yml
This is the attempt to fix `GLIBC` issue for conda by using pytorch provided image
=> Make conda use manylinux image from pytorch to support lower glibc

docs/source/index.rst, docs/source/torchdata.datapipes.utils.rst, test/dataloader2/test_mprs.py, test/test_iterdatapipe.py, test/test_serialization.py, torchdata/datapipes/iter/__init__.py, torchdata/datapipes/iter/__init__.pyi.in, torchdata/datapipes/iter/util/prefetcher.py, torchdata/datapipes/utils/__init__.py, torchdata/datapipes/utils/pin_memory.py
Cherry-pick #1014
Summary:
Fixes https://github.com/pytorch/data/issues/1013
- Simplify the control flow of prefetcher
- Delay Exception raised from thread worker to main thread in `__iter__`
- Stop prefetching whenever Exception is received
- As long as `stop_iteration` is not turned on or `buffer` is not empty, continue yielding data from `__iter__`.
- Add serialization test
- Add `PinMemory` DataPipe
-  `is_replciable() -> False` to keep it in the main process
- Add unit tests
- Update `test_proto_multi_rs.py` to `test_mprs.py`
Pull Request resolved: https://github.com/pytorch/data/pull/1014
Differential Revision: D43329696
fbshipit-source-id: da4326dbe2388f4e23b9a1a3a5c43da09d29185a
=> Update Prefetcher and Implement PinMemory IterDataPipe (#1014)

examples/vision/laion5b.py
Cherry-pick of #1034
Summary:
This is an example that uses Datapipes to download and preprocess the [laion5b](https://laion.ai/blog/laion-5b/)-dataset (to be more precise [this subset](https://huggingface.co/datasets/laion/laion2B-en-joined)). Also uses Dataloader2 for multiprocessing.
- Load metadata from Huggingface and filter
- Load images from the urls
- access metadata of image and print out label and copyright information
Unfortunately I made a mistake while rebasing in https://github.com/pytorch/data/issues/1017 so I had to reopen the PR.
Pull Request resolved: https://github.com/pytorch/data/pull/1034
Differential Revision: D43463022
fbshipit-source-id: 2f1f2b8bcb3abee15a1935431a497532b95b1c8d
Please read through our [contribution …
=> [Release 0.6.0] Add laion5b-example with Dataloader2 (#1034)

test/dataloader2/test_dataloader2.py, torchdata/_utils.py, torchdata/dataloader2/communication/eventloop.py, torchdata/dataloader2/communication/iter.py, torchdata/dataloader2/communication/map.py, torchdata/dataloader2/communication/messages.py, torchdata/dataloader2/communication/protocol.py, torchdata/dataloader2/reading_service.py, torchdata/datapipes/iter/util/combining.py
Cherry-pick: #1036
Summary:
Partially fixes https://github.com/pytorch/data/issues/969
- Add `ExceptionWrapper` to attach traceback to the Exception
- Reason: traceback is unserializable. So, it has to be passed by string
- In order to provide informative Error message, pass name for each process like `dispatching process` and `worker process <id>`.
- Add tests to validate Error propagation from the dispatching process
- parametrize the tests
- Fix a bug for `round_robin_demux` to return a list of DataPipe rather than a single DataPipe when `num_of_instances` is 1.
Pull Request resolved: https://github.com/pytorch/data/pull/1036
Differential Revision: D43472709
fbshipit-source-id: e5c9e581ca881f523fb568b6f46bf16ecfc243d2
=> Attach traceback to Exception & Test disatpching process (#1036)

.github/workflows/_build_test_upload.yml
Summary:
This create a bad dependency chain, do not do that please
Tested on my local mac
Pull Request resolved: https://github.com/pytorch/data/pull/1064
Reviewed By: seemethere, NivekT
Differential Revision: D43780624
Pulled By: atalman
fbshipit-source-id: c61b1887881a91c41702ba2efbd1246b753ec99f
=> ci: Do not install conda-build from conda-forge (#1064)

.github/workflows/build-conda-m1.yml, .github/workflows/build-wheels-m1.yml, test/dataloader2/test_dataloader2.py, test/test_serialization.py, torchdata/dataloader2/dataloader2.py, torchdata/datapipes/iter/util/cacheholder.py, torchdata/datapipes/iter/util/converter.py, torchdata/datapipes/iter/util/dataframemaker.py
Fix arm64 builds by building using source
test
tests
fix_testPlease read through our [contribution guide](https://github.com/pytorch/data/blob/main/CONTRIBUTING.md) prior to
-
-
Summary:
Pull Request resolved: #1222
Changes from the PyTorch repo (D53082622) broke torchdata. I updated the dill_available API for torchdata to keep everything in sync.
Reviewed By: atalman, ejguan
Differential Revision: D53086369
fbshipit-source-id: 7344c4cd3205a38689722330721257b5a01bd32f
=> Cherry picks for 0.7.2

test/test_remote_io.py, test/test_s3io.py, torchdata/datapipes/iter/load/README.md, torchdata/datapipes/iter/load/s3io.py
Adding deprecation message about S3 IterDataPipes and pointing to https://github.com/awslabs/s3-connector-for-pytorch.
Cc @jamesbornholt, @dnauti
=> Add message about s3 iterdata pipes deprecation

test/stateful_dataloader/test_incremental_state.py, test/stateful_dataloader/test_state_dict.py, torchdata/stateful_dataloader/__init__.py, torchdata/stateful_dataloader/incremental_state.py, torchdata/stateful_dataloader/stateful_dataloader.py, torchdata/stateful_dataloader/worker.py
Summary: Transfer of full state from worker to main process can be expensive if the state is very large. In order to alleviate the cost of state transfer, maintain a flattened state map in the worker process and send only the key/value that have changed to the main dataloader process where the full state is reconstructed with the changes received from the workers.
Test Plan: Unit tests
Reviewers:
Subscribers:
Tasks:
Tags:Please read through our [contribution guide](https://github.com/pytorch/data/blob/main/CONTRIBUTING.md) prior to
-
-
=> Implement incremental state transfer from worker to dataloader process #1262

test/stateful_dataloader/test_incremental_state.py, torchdata/stateful_dataloader/incremental_state.py
Flatten could return None but result of flatten was recursively used for updating the flatten map. This caused an error when the value of the dict is None. Handling that case now and also added unit tests to capture that scenario
-
-
=> Incremental state: fix flatten None handling

.github/workflows/ci.yml, .github/workflows/stateful_dataloader_ci.yml, test/stateful_dataloader/test_incremental_state.py, test/stateful_dataloader/test_state_dict.py, torchdata/datapipes/iter/load/s3io.py, torchdata/stateful_dataloader/__init__.py, torchdata/stateful_dataloader/stateful_dataloader.py, torchdata/stateful_dataloader/worker.py
When state_dict is requested before an iterator is created, we currently return an empty dict. This does not reflect a true initial state of the workers, and may break assumptions made by DCP.
This update will guarantee that anytime state_dict is requested, you will get a "full" state_dict that includes main state, and all worker initial states, including dataset/iterator states. We achieve this by including an ack signal from the workers which includes an initial state_dict. The main process now waits for these acks and stores the initial states for any subsequent state_dict requests, as well as for resetting the iterator.
* …
=> Update state_dict() request at time 0 to include worker state

test/stateful_dataloader/test_incremental_state.py, test/stateful_dataloader/test_state_dict.py, torchdata/stateful_dataloader/incremental_state.py
Fixes the case where tensor is returned as the state instead of a dict. This was failing because the tensor object was being used as a bool check for the walrus operator and that failed. Instead just do regular fetch and not None comparison.
Added unit tests in all the layers to cover this
Fixes #{1271}
-
-
=> Handle case where state is a tensor

.github/workflows/stateful_dataloader_ci.yml, test/requirements.txt, test/stateful_dataloader/test_hugging_face.py
Test against HF datasets main to catch regressions against https://github.com/huggingface/datasets/pull/6658 
* adds HF test
* datasets req in test/requirements to pull from github main
-
-
=> Add huggingface regression test

torchdata/__init__.py, torchdata/dataloader2/__init__.py, torchdata/datapipes/__init__.py
See https://github.com/pytorch/data/issues/1196 
Adds deprecation warning for datapipes, dataloader2, and janitor imports from torchdata
Some quick tests:
-
-
=> add deprecation warning for deprecated modules

test/stateful_dataloader/test_state_dict.py, torchdata/stateful_dataloader/stateful_dataloader.py, torchdata/stateful_dataloader/worker.py
Context:
For iterable datasets, state can be defined both at dataset level and also in the iterator. In the state_dict that is vended, this dataset_state is stored in dataset_state and iterator state is stored in fetcher_state::dataset_iter_state.
For a dataset which also acts as an iterator, initially the identical state was saved in both places which was wasteful. This was fixed in https://github.com/pytorch/data/pull/1258 where the state was saved only once in fetcher_state::dataset_iter_state.
But this was swapped in https://github.com/pytorch/data/pull/1273.
This is being swapped back to its original state to make sure the state variables can be initialized even in the iter method (which is the only place where it can access variables such as …
=> Save state in dataset_iter_state when dataset is also an iterator

torchdata/stateful_dataloader/sampler.py, torchdata/stateful_dataloader/stateful_dataloader.py
Fixes #1280 
Currently we patch torch.utils.data's BatchSampler and RandomSampler in order to add statefulness to them. This is way too aggressive.
Instead let's just fork the dataloader __init__ for now and merge back into core once the time is right.
* Stop patching torch.utils.data's BatchSampler and RandomSampler
* Fork dataloader's __init__ and pass in the Stateful BatchSampler and RandomSampler instead.
-
-
=> fork dataloader __init__ instead of patching samplers

torchdata/stateful_dataloader/stateful_dataloader.py
StatefulDataLoader import failed in torchtitan here - https://github.com/pytorch/torchtitan/actions/runs/9784768290/job/27016395174. 
The error was T_co import from dataloader failed. The failure happened because of this change - https://github.com/pytorch/pytorch/pull/129885 which renamed T_co to _T_co. 
Instead of import T_co from dataloader, define and use it locally within StatefulDataLoader
=> Define and use _T_co locally instead of importing from torch.utils.data DataLoader

test/requirements.txt
=> Match the numpy version change in main branch test requirements

.github/workflows/_build_test_upload.yml, .github/workflows/test_release.yml
Cherry pick doc build fix PR (https://github.com/pytorch/data/pull/1297) to main 
-
-
=> Fix doc build (#1297)

docs/Makefile, docs/source/dp_tutorial.rst, docs/source/index.rst, docs/source/torchdata.stateful_dataloader.rst, torchdata/dataloader2/reading_service.py, torchdata/stateful_dataloader/stateful_dataloader.py
title. Also added docs for stateful dataloader api (including changes from https://github.com/pytorch/data/pull/1301)
Now the make html command works
Page preview
-
=> fix docs, make sure docs build

docs/source/index.rst, docs/source/stateful_dataloader_tutorial.rst
title. Added tutorial docs on how to use stateful dataloader to the docs
-
-
=> Add stateful dataloader tutorial docs

docs/Makefile, docs/source/dp_tutorial.rst, docs/source/index.rst, docs/source/stateful_dataloader_tutorial.rst, docs/source/torchdata.stateful_dataloader.rst, torchdata/dataloader2/reading_service.py, torchdata/stateful_dataloader/stateful_dataloader.py
* Cherry pick doc change commits from main branch
---------
Co-authored-by: atalman <atalman@fb.com>Please read through our [contribution guide](https://github.com/pytorch/data/blob/main/CONTRIBUTING.md) prior to
-
-
* fix docs, make sure docs build
* adding stateful dataloader docs
=> Cherry pick docs changes from main branch

docs/source/conf.py
* add deprecation banner to sphinx docs. Adding this in rst_prolog pre-pends it to every page
-
-
Tested by building locally
=> Add datapipes deprecation warning banner to docs

docs/source/conf.py
Cherry pick docs banner change
```
cd docs
make html
open build/html/index.html
```
screenshot:
-
-
=> Add datapipes deprecation warning banner to docs (#1312)

.github/workflows/stateful_dataloader_ci.yml, test/stateful_dataloader/test_dataloader.py, test/stateful_dataloader/test_sampler.py, torchdata/stateful_dataloader/sampler.py
Fixes #1269 
- `torchdata/stateful_dataloader/sampler.py` : Added new classes `StatefulDistributedSampler` and `_StatefulDistributedSamplerIterator`
- `test/stateful_dataloader/test_dataloader.py` new tests for `StatefulDistributedSampler`
=> Make DistributedSampler stateful

.github/workflows/nightly_release.yml, .github/workflows/test_release.yml
Unsure if CI will succeed without this, I don't see it referenced in many other pytorch repos though, and none of our tests which build seem to include it either. 
From this workflow:
https://github.com/pytorch/data/actions/workflows/nightly_release.yml 
[Invalid workflow file: .github/workflows/nightly_release.yml#L18](https://github.com/pytorch/data/actions/runs/11031708385/workflow)
The workflow is not valid. .github/workflows/nightly_release.yml (Line: 18, Col: 41): Invalid secret, PYTORCH_BINARY_AWS_ACCESS_KEY_ID is not defined in the referenced workflow. .github/workflows/nightly_release.yml (Line: 19, Col: 45): Invalid secret, PYTORCH_BINARY_AWS_SECRET_ACCESS_KEY is not defined in the referenced workflow.
Update digging through blame, I can see that test_release and pull_release …
=> Fix nightly build. They've been failing due to missing secrets

.github/workflows/_build_test_upload.yml
https://github.com/pytorch/data/actions/runs/11357418885/job/31590502866 
Test Release run is failing to get pytorch 2.5.0 due to pip command. Tested locally:
With current command:
```
pip install --pre torch==2.5.0 -f https://download.pytorch.org/whl/test
...
Looking in links: https://download.pytorch.org/whl/test
ERROR: Could not find a version that satisfies the requirement torch==2.5.0 (from versions: 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.4.1)
ERROR: No matching distribution found for torch==2.5.0
```
With updated command:
```
pip install --pre torch==2.5.0 --index-url https://download.pytorch.org/whl/test/cpu
...
Looking in indexes: https://download.pytorch.org/whl/test/cpu
Collecting torch==2.5.0
Using cached https://download.pytorch.org/whl/test/cpu/torch-2.5.0%2Bcpu-cp312-cp3 …
```
=> fix test install path

docs/source/conf.py
Fixes #1344 
Docs were failing to build, see https://github.com/pytorch/data/actions/runs/11383648141/job/31670214305 
Tested: 
```
> cd docs
> make clean && make html
Running Sphinx v5.0.0
/data/users/andrewkh/data
[autosummary] generating autosummary for: index.rst, stateful_dataloader_tutorial.rst, torchdata.stateful_dataloader.rst
loading intersphinx inventory from https://graphviz.readthedocs.io/en/stable/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 3 source files that are out of date
updating environment: [new config] 3 added, 0 changed, 0 removed
reading sources... [100%] torchdata.stateful_dataloader
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... …
```
=> fix doc build on main

.github/workflows/_build_test_upload.yml, .github/workflows/nightly_release.yml
Current windows wheel build is failing on Nightly because it's trying to build S3 binaries, but we don't have any native extensions anymore. This leaves most of the code intact but just disables the envvar.
Example failing nightly:
https://github.com/pytorch/data/actions/runs/11438773492 
Example passing job build step (upload fails because of branch protection, but that's fine)
https://github.com/pytorch/data/actions/runs/11444540802/job/31839644282
=> Fix windows wheel build

torchdata/nodes/map.py
parallel map test_exception_handling occasionally hangs during shutdown, particularly when test suite is running many instances in parallel. This issue became apparent when running buck test
We set background utility threads as daemons to bring them down when the job ends.
=> Fix unclean shutdown by setting daemon property on utility threads

test/nodes/test_adapters.py, test/nodes/utils.py, torchdata/nodes/__init__.py, torchdata/nodes/adapters.py, torchdata/nodes/base_node.py
Drop the subclassing of IterableDataset, let's not pull these old weird decisions in, eg https://github.com/pytorch/pytorch/issues/120139 
Instead we add simple adapter class to cast if someone wants to stick this into a dataloader for some reason.
Also add some convenience adapters to go the other way, which take Map/Sampler or Iterable style datasets and implement the `iterator` interface for BaseNode
TestPlan: `pytest --no-header -v test/nodes/ --full-trace` passes
=> Don't subclass IterableDataset, and add two-directional adapters instead

benchmarks/torchvision_classification/helpers.py, benchmarks/torchvision_classification/train.py
Removes references to dataloader v2.
Fixes [#{1350}](https://github.com/pytorch/data/issues/1350)
-
-
=> Remove dataloader v2 usage in data/benchmarks

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
=> Update PR Template and Contributors guide for nodes

.github/workflows/nodes_ci.yml, .github/workflows/stateful_dataloader_ci.yml, test/nodes/test_adapters.py, test/nodes/test_base_node.py, test/nodes/test_batch.py, test/nodes/test_map.py, test/nodes/test_pin_memory.py, test/nodes/test_prefetch.py, test/nodes/test_snapshot_store.py, test/nodes/utils.py, test/requirements.txt, torchdata/nodes/__init__.py, torchdata/nodes/_apply_udf.py, torchdata/nodes/_populate_queue.py, torchdata/nodes/adapters.py, torchdata/nodes/base_node.py, torchdata/nodes/batch.py, torchdata/nodes/map.py, torchdata/nodes/pin_memory.py, torchdata/nodes/prefetch.py, torchdata/nodes/snapshot_store.py, torchdata/nodes/types.py
Adds state_dict/load_state_dict interface to torchdata.nodes.base_node. Update all existing node definitions to save/load state correctly.
```
BaseNode.state_dict() -> Dict[str, Any]: ...
""" Can be called at any time, on the BaseNode, and return a dictionary representing state_dict that can be
passed to load_state_dict. Calling this will return state_dict of the last result of BaseNode.__iter__()"""
BaseNode.load_state_dict(state_dict: Dict[str, Any]): ...
""" When called with the output of BaseNode.state_dict(), affects the next iterator returned by BaseNode.__iter__()
""" 
```
```
BaseNode.iterator(initial_state: Optional[Dict[str, Any]]) -> Iterator[T]: ...
""" Resuming state is only possible at iterator instantiation. Developers must explicitly define how to handle non-null …
```
=> Add state management to torchdata.nodes

test/nodes/utils.py, torchdata/nodes/base_node.py
Adds docstring about saving/loading state_dict at end-of-iteration (either after or just before StopIteration is thrown). 
See Docstring for details on the rationale behind this change.
TL;DR - If you load a state_dict from end-of-epoch, calling next(iter(node)) on it would throw stop iteration. This is unexpected for the (very) common case of saving state_dict at end of epoch, and loading it and expecting it to restart from the beginning of the next epoch, so the old default behaviour is to catch that stop iteration (through has_next()), and restart the iterator automatically.
The problem is that this breaks down when BaseNodes actually _need to know_ that StopIteration is going to be thrown, for example, multi-dataset samplers that need to handle end-of-iteration from one of their …
=> Changes default behaviour of StopIteration immediately after load_state_dict to be false

torchdata/nodes/__init__.py
Adds SamplerWrapper to `torchdata/nodes/__init__.py`
=> add SamplerWrapper to init

test/nodes/test_map.py, test/nodes/test_pin_memory.py, test/nodes/test_prefetch.py, test/nodes/test_snapshot_store.py, test/nodes/utils.py, torchdata/nodes/_populate_queue.py, torchdata/nodes/loader.py, torchdata/nodes/map.py, torchdata/nodes/pin_memory.py, torchdata/nodes/snapshot_store.py
Fixes some state-management edge cases.
1) calling state_dict before a pre-fetcher was not capturing a snapshot correctly. We now send a snapshot (or initialization error) as an "ack" during _populate_queue and _pin_memory startups to handle this scenario correctly. 
2) calling `loader.state_dict(); iter(state_dict)` would call `reset()` twice on the underlying nodes (once for initial state_dict), whereas running `iter(state_dict); loader.state_dict()` would only call once since `loader._it` is already instantiated. Added a flag to handle these cases.
Test plan:
Create `class StatefulRangeNode(BaseNode)` which tracks number of resets, and use these in `test_map, test_prefetch, test_pin_memory` state management tests. Those tests failed before the changes and succeed now.
=> initial state fix for pin_memory and SingleThreadedMapper

.github/workflows/test_release.yml
This change has to exist for both the main as well as the release cut branch.
Will rebase this on top of https://github.com/pytorch/data/pull/1371 once that lands.
Reference: https://www.internalfb.com/wiki/Media_DataLoader/Development/torchdata_release_process/
=> update test_release.yml to v0.10

.github/workflows/_build_test_upload.yml
We tried to setup a test workflow for v10 release, but it failed because windows has no support for 3.13 in torch.
Flow: https://github.com/pytorch/data/actions/runs/12208526204/job/34061897521#step:8:300
We believe that is because the flow config `_build_test_upload.yml` doesn't exclude 3.13 for windows. This PR is adding that.
I tried to test the workflow with this change by running the test release workflow on the branch `divyanshk/exclude_3.13_...` but that doesn't work. Mostly because of the filtering rules built in the config (https://github.com/pytorch/data/actions/runs/12209869119/workflow#L31).
Edit: `build_test_upload` got kicked by this PR and succeeds https://github.com/pytorch/data/actions/runs/12210112227/job/34065795491?pr=1386 (i.e. excludes 3.13 and pure for windows)
=> Exclude 3.13 for windows on release v10

README.md, docs/source/index.rst, docs/source/torchdata.nodes.rst
Clone the repo on local, created the environment, updated the `/docs` folder, then`make html` and `sphinx-serve -b build`.
=> add new torchdata.nodes doc file

README.md, docs/source/index.rst, docs/source/torchdata.nodes.rst
* add new torchdata.nodes doc file
* update main readme.md, move content of nodes readme.md to torchdata.nodes.rst
* main readme
* udpate readme
=> Cherry picking PR#1390 onto release branch

test/smoke_test/smoke_test.py, torchdata/nodes/samplers/multi_node_weighted_sampler.py
1) update smoke test to include an import from torchdata.nodes
2) minor doc string fix
=> update smoke test

examples/nodes/imagenet_benchmark.py
Adds Imagenet benchmarking to examples/nodes
Test plan, tried a handful of options with Python 3.13t build on Linux eg:
```
python -Xgil=0 examples/nodes/imagenet_benchmark.py -d ~/local/imagenet_1k/train/ --max-steps 1000 --loader thread --shuffle=True --in-order=True
Running benchmark with args=Namespace(loader='thread', num_workers=4, batch_size=16, in_order=True, shuffle=True, max_steps=1000, max_duration=60, warmup_steps=0, pin_memory=False, imagenet_dir='/home/andrewkh/local/imagenet_1k/train/')...
create iter took 0.020316815935075283 seconds
0 / 1000, 5.683861672878265e-06 seconds elapsed
100 / 1000, 1.8675199393182993 seconds elapsed
200 / 1000, 3.7960099279880524 seconds elapsed
300 / 1000, 5.413591359741986 seconds elapsed
400 / 1000, 7.112115032039583 seconds elapsed
500 / …
```
=> add benchmark imagenet code example

torchdata/nodes/base_node.py, torchdata/nodes/samplers/multi_node_weighted_sampler.py
Fixes https://github.com/pytorch/data/issues/1410
Confirmed by running docs on local machine there bullets work fine, and Returns format correctly.
=> Fix docs formatting

torchdata/nodes/pin_memory.py
- If you are adding a new node, ensure you read that section in the contribution guide, as it includes requirements for
functionality and testing.
- Not related
- Add privateuse1 situation support for _pin_memory property in PinMemory class
=> remove unused _pin_memory property in PinMemory class 

test/nodes/test_batch.py, torchdata/nodes/__init__.py, torchdata/nodes/batch.py
Required for #1415 
* Add Unbatcher node and unit test
-
-
=> Add unbatcher node

.github/workflows/_build_test_upload.yml, .github/workflows/lint.yml
Github is [deprecating artifact actions v3.](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/)
Made the following changes:
`actions/setup-python@v4 -> actions/setup-python@v5`
`actions/checkout@v3 -> actions/checkout@v4`
`actions/download-artifact@v3 -> actions/download-artifact@v4`
`actions/upload-artifact@v3 -> actions/upload-artifact@v4`
refs:
1. https://github.com/pytorch/executorch/pull/7573
2. https://github.com/pytorch/test-infra/pull/5877
=> Update action versions

test/nodes/test_multi_node_weighted_sampler.py, torchdata/nodes/samplers/multi_node_weighted_sampler.py, torchdata/nodes/samplers/stop_criteria.py
This PR adds support for continuous cycling through each base node in multi node weighted sampler. With the current setup this was each to extend. We do cycle through each node to support `StopCriteria.CYCLE_UNTIL_ALL_DATASETS_EXHAUSTED`, for `StopCriteria.CYCLE_FOREVER` we skip raising a `StopIteration`.
This should be functionally equivalent to having an infinite sampler plugged on top of each base dataset. 
The dataset order (as defined by `weights`) remains the same.
=> Make Multi Node sampler cycle forever

test/nodes/test_multi_node_weighted_sampler.py
Due to the stochastic nature of the MultiNodeWeightedSampler and the way StopIteration is called when multiple datasets are involved, some test results are dependent on the OS/seed. Trying to fix seed and change testing conditions with this PR.
=> Fix MultiNodeWeightedSampler tests

test/stateful_dataloader/test_dataloader.py, torchdata/stateful_dataloader/stateful_dataloader.py
Fixes #1414
- Adds the changes from https://github.com/pytorch/pytorch/pull/141833 and https://github.com/pytorch/pytorch/pull/142324 to the Stateful DL
- Adds a warning log to mention that state management may not work as expected.
The tests I've added were the exact same ones from the main PyTorch repo, so the functionality of the flag is the exact same. There was a few changes required to be compatible with the few slight differences of the `_StatefulMultiProcessingDataLoaderIter`.
I have also tested some simple cases of stopping/resuming both an index and iterable ds and it seems to work correctly (the same types that are used in the new test cases). I haven't added extra tests for that into this PR just to keep the size manageable, but would add them in a follow up PR as well as …
=> [Stateful DL] Add out of order implementation

test/stateful_dataloader/test_state_dict.py, torchdata/stateful_dataloader/stateful_dataloader.py
Follow up to #1423
- Add tests for state management of both index datasets and iterable datasets when `in_order=False`
- Remove warning logs about `in_order=False`
State management with `in_order=False` actually _just works_ which is really nice.
I'm happy to keep the warning logs in for longer if we'd like to err on the side of caution. And please let me know if there are any other test cases I should add.
=> Add tests for out of order with checkpointing

test/stateful_dataloader/test_state_dict.py, torchdata/stateful_dataloader/sampler.py, torchdata/stateful_dataloader/stateful_dataloader.py
Add tests to reproduce and fix #1437
=> Fix end of epoch StatefulDataLoader restart

test/stateful_dataloader/test_sampler.py, test/stateful_dataloader/test_state_dict.py, torchdata/stateful_dataloader/sampler.py
Currently we are fixing the seed for `generator` in `RandomSampler` as 1.
This leads to the generator not changing even when torch.manual_seed() seed is changed. 
For the RandomSampler in `torch.utils.data.sampler`, they use `seed = int(torch.empty((), dtype=torch.int64).random_().item())`. Using the same here.
Fixes #1440
=> Using system generated seed in RandomSampler

test/nodes/test_filter.py, torchdata/nodes/__init__.py, torchdata/nodes/filter.py
- If you are adding a new node, ensure you read that section in the contribution guide, as it includes requirements for
functionality and testing.
- Adding `Filter` node and its test (for now)
- Possibly TBD after discussion - as mentioned in #1452, I'd add `Shuffler`, `Header`, `Cycler` if the maintainers are okay with it.
=> Add `Filter`

torchdata/nodes/map.py, torchdata/nodes/snapshot_store.py
=> Fixing docstrings, add thread names to help in debugging, add a missing stop check

torchdata/nodes/pin_memory.py
Summary:
This fixes the CI error introduced in the diff below this diff. Landing the fix here, will also see how this kicks off a PR in OSS repo.
The error was not caught in the CI of OSS because we might not have GPU code unit testing - need to fix that!
Differential Revision: D71564699
=> fix missing __name__ attribute in partial function

torchdata/nodes/map.py
The daemonic _read_thread causes issues at exit in certain circumstances in which the `source` object that it refers to does not get collected by the garbage collector. Allowing the user to toggle this thread to be non-daemonic prevents this issue.
=> Add flag for non-daemonic _read_thread in ParallelMapper

test/nodes/test_multi_node_round_robin_sampler.py, torchdata/nodes/samplers/multi_node_round_robin_sampler.py
This PR attempts to add a new sampler, Round robin sampler.
=> Multidataset round robin sampler

test/nodes/test_map.py, torchdata/nodes/map.py
Current `ParallelMapper` has the following model:  
Arrows and dotted line represent the main process
---->----(spawn a background read_thread)---->---(start explicit transformation threads)---->---(spawn a background sort_thread)---->----
We are updating that to be:
---->----(spawn a background read_thread)  ---->----(start transformation threads within a threadpoolexecutor)---->----(spawn a background sort_thread) ---->----
Here we do not update the `method=process` workflow.
Unit tests looks good on local. Tested GPU unit tests internally. 
Benchmarked thread pool vs explicit thread creation for transformation, almost identical performance in both settings.
=> Replace launching explicit threads with a threadpoolexecutor

docs/source/getting_started_with_torchdata_nodes.rst
Hi, I am just fixing an example where `torch.utils.data.RandomSampler` is not properly imported.
=> Fix an example in docs by properly importing torch.utils.data.RandomSampler

torchdata/nodes/map.py
@ramanishsingh helped identify some Github UI hanging in older python versions. This diff adds explicit shutdown to ensure thread pool executor doesn't stay open even after all threads are completed.
=> add explicit shutdown calls

test/nodes/test_multi_node_round_robin_sampler.py, torchdata/nodes/samplers/multi_node_round_robin_sampler.py
Currently MultiNodeRoundRobinSampler takes the source nodes as a dict. We do not save the keys to the datasets in our state dict. This can lead to inconsistencies when reloading state dict (for e.g., if someone starts with 4 datasets but then only re-instantiates with 3). 
Adding following things
1. We keep the keys  to the datasets provided in MDS RR sampler and then save them in state dict. On `reset` we make sure the keys are the same and in order.
2. Also allowing the users to provide the dataset nodes in a list. This simplifies the process for them. However, it can cause issues if the users are not careful about providing the same order of datasets when re-instantiates and loading state_dict. For that, we log a warning that they need to provide the datasets in the same order.
In the …
=> Maintain and check dataset keys in MultiNodeRoundRobinSampler

torchdata/nodes/map.py
Currently resetting `ParallelMap` kills threads with `del self._it`, which is not guaranteed to immediately call `self._it.__del__` and thus `._shutdown` method. It leads to an extra living read thread. This extra thread can consume extra items from `self.source` node, which will be missing from new `self._it`
I faced this issue with `lightning.pytorch` training. I could not figure out, if lightning just calls `iter` twice in a short time, or increases ref count of the old iterator object somehow, but as a matter of fact I have two running read threads, which breaks my pipeline at the first batch.
Add explicit `self._it._shutdown()` into `reset` method. This fixes described bug
=> Explicit iterator shutdown

torchdata/nodes/map.py
This PR adds 
* builds on top of previous shutdown PRs (https://github.com/pytorch/data/pull/1482, https://github.com/pytorch/data/pull/1477)
* adds in explicit shutdowns in single-threaded-mapper
* removes daemonic reading arg
Tested this in meta CI + Github Ci - no hanging unit tests. Will test with production job as well.
=> remove daemon threads

test/nodes/test_multi_node_round_robin_sampler.py, torchdata/nodes/samplers/multi_node_round_robin_sampler.py
This PR adds the option to tag the output items of MultiNodeRoundRobinSampler. 
We have added a new argument `tag_output` which accepts a boolean or a size 2 tuple. 
If tag_output is true, output item is tagged as {"dataset": dataset_name, "item": item}. If a tuple is provided, the first element is used as the dataset key and the second one is used as the item key.
=> Tag outgoing batch in round robin sampler

test/nodes/test_multi_node_weighted_sampler.py, torchdata/nodes/samplers/multi_node_weighted_sampler.py
Summary: Adding a new option to make multi node sampler emit dicts with dataset keys
Reviewed By: ramanishsingh
Differential Revision: D73187135
=> Make parallel mapper work on dataset specific transformations

test/nodes/test_multi_node_weighted_sampler.py, test/nodes/test_snapshot_store.py, torchdata/nodes/map.py, torchdata/nodes/samplers/multi_node_weighted_sampler.py, torchdata/nodes/snapshot_store.py
This PR replaces reading thread and sorting thread with submissions to a thread pool executor. After this the parallelmapper will entirely be based on a thread pool rather explicit thread creation. 
We continue to maintain `num_workers + 2` and the pool size, with `num_workers`  being a knob for users to tune the threads to use for applying transformations.
=> Threadpoolexecutor in map

test/nodes/test_map.py, torchdata/nodes/map.py
Summary:
This option will come handy when we add an explicit shutdown method which should be non-blocking and doesn't allow pending tasks to proceed.
This change is backwards compatible.
Differential Revision: D75312613
=> Add non-blocking option in thread pool executor

tools/setup_helpers/extension.py
=> Clean extension.py

test/nodes/test_map.py, test/nodes/test_pin_memory.py, test/nodes/test_prefetch.py, torchdata/nodes/base_node.py, torchdata/nodes/map.py, torchdata/nodes/pin_memory.py, torchdata/nodes/prefetch.py
Summary:
This diff stack adds an optional method to the `base_node` for explicit shutdown. This is not BC-breaking as it not mandatory to implement `shutdown`, although encouraged.
```
data_node1 = IterableWrapper(DummyIterableDataset(1000000))
node1 = Prefetcher(data_node1, prefetch_factor=1000)
/ ... do some user code using node1 ... /
data_node2 = IterableWrapper(DummyIterableDataset(10000))
node2 = Prefetcher(data_node2, prefetch_factor=500)
/ ... training loop ... /
```
In the above snippet, we create two nodes with the second node actually used in training. The first one is created but not really iterated upon. Now, this is an anti-pattern, i.e. users should not be ideally doing this. Because the first node (`node1`), although not used has led to the creation of a background thread …
=> Add shutdown method to nodes

test/nodes/test_multi_node_weighted_sampler.py
Summary:
Tests which iterate over multiple epochs often lead the node 'open' due to a force reset at the end of the for loop. These tests were hanging when I make the singlethreadedmapper a non-daemon. Now, I think it is important for the singlethreadedmapper 's worker thread to be a daemon to ensure a background process which populates the buffer. This property is what the prefetcher useful. This lead to developing an explicit shutdown method to close of any working processes/threads in the background once that chain of nodes is not required. See D75241769.
I am adding explicit shutdown to certain unit tests here for sake of completeness. It doesn't change the behavior of the unit tests.
Differential Revision: D75241767
=> Update tests to do explicit shutdowns
